name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
      - name: Install dependencies
        run: python -m pip install --upgrade pip tox
      - name: Build font
        run: python -m tox -e build
      - name: Upload TTF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/MeterialSymbols.ttf
          asset_name: MeterialSymbols.ttf
          asset_content_type: font/ttf
      - name: Upload WOFF2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/MeterialSymbols.woff2
          asset_name: MeterialSymbols.woff2
          asset_content_type: font/woff2
      - name: Compress all results
        run: zip dist/MeterialSymbols dist/*
      - name: Upload ZIP
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/MeterialSymbols.zip
          asset_name: MeterialSymbols.zip
          asset_content_type: application/zip
