name: CI (Website)

on:
  push:
    branches: [main, develop]
    paths:
      - "website/**"
      - ".github/workflows/ci-website.yml"
      - ".github/actions/setup-project/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "website/**"
      - ".github/workflows/ci-website.yml"
      - ".github/actions/setup-project/**"

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
      - run: pnpm run format
        working-directory: website

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
      - run: pnpm run lint
        working-directory: website

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
      - run: mkdir dist
      - run: pnpm run gen:cf-types
        working-directory: website
      - run: pnpm run check
        working-directory: website

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
      - run: mkdir dist
      - run: pnpm run build
        working-directory: website
