name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "website/**"
      - ".github/workflows/ci-website.yml"
  push:
    branches:
      - main

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
      - name: Install dependencies
        run: python -m pip install --upgrade pip tox
      - name: Format
        run: python -m tox -e format

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
      - name: Install dependencies
        run: python -m pip install --upgrade pip tox
      - name: Lint
        run: python -m tox -e lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
      - name: Install dependencies
        run: python -m pip install --upgrade pip tox
      - name: Typecheck
        run: python -m tox -e typecheck

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
      - name: Install dependencies
        run: python -m pip install --upgrade pip tox
      - name: Build
        run: python -m tox -e build
